---
title: "Antler ~ DNAmAge"
author: "RUMIANOWSKI 0."
date: "21/04/2022"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
rm(list = ls()) # nettoyage de l'environnement de travail


# Chargement du jeu de données --------------------------------------------

library(readxl) # pour charger les fichiers excel
library(tidyr)
library(tibble)
library(dplyr)
library(purrr)
library(ggplot2)
library(lme4)
library(naniar)
library(UpSetR)
library(corrplot)
library(stringr)

```



```{r, message=FALSE, warning=FALSE}
data_antler = read_excel("data/Dataset_ODIN_160422.xlsx", skip = 0, na = "NA") %>% 
  mutate(PlateNumber = as.factor(PlateNumber), 
         Batch_number = as.factor(Batch_number),
         ProblemDNA_Concentration = as.factor(ProblemDNA_Concentration),
         PlateTelomere  = as.factor(PlateTelomere),
         DNAmAgeLOO = as.numeric(DNAmAgeLOO),
         `AgeAccelLOO(ComputedUCLA)` = as.numeric(`AgeAccelLOO(ComputedUCLA)`),
         RightAntlerLength    = str_remove(RightAntlerLength, "_broken") %>% 
           as.numeric(),
         AntlerLength = map2_dbl(.x = Left_AntlerLength, 
                                 .y = RightAntlerLength,
                                 .f = function(x, y){
                                   if(is.na(x))
                                     return(y)
                                   else if(is.na(y))
                                     return(x)
                                   else
                                     return(max(x, y))
                                 }
         ),
         AgeClass = cut(Age, breaks = c(0,1,4,8,25)) %>% 
           as.character(),
         Age_2 = Age**2) %>% 
  rename(Year = YearCapture,
         Day = JulianCaptureDate,
         Cohort_Type = `Cohort_Quality_Type(Good/Bad)`,
         DNAmAge = DNAmAgeLOO,
         AgeAccelLOO = `AgeAccelLOO(ComputedUCLA)`,
         Weight = WeightAnimal.kg,
         ProblemDNA  = ProblemDNA_Concentration,
         RTL = QC_RTL) %>% 
  select(Pop_Id, Year, Day, 
         Cohort, Cohort_Type, Population, 
         Age, Age_2, AgeClass, Weight, AntlerLength,
         RTL, DNAmAge, AgeAccelLOO, ProblemDNA)


```


```{r, message=FALSE, warning=FALSE}
vis_miss(data_antler)
```


```{r, message=FALSE, warning=FALSE}
ggplot(data_antler, aes(x=Age, color=Population)) +
  geom_histogram(fill="white")

```
```{r, message=FALSE, warning=FALSE}
plot(data_antler[, c("Age","Weight", "AntlerLength",
         "RTL", "DNAmAge", "AgeAccelLOO")] , pch=20 , cex=1.5 , col="#69b3a2")



```
```{r, message=FALSE, warning=FALSE}

```
```{r, message=FALSE, warning=FALSE}

```
```{r, message=FALSE, warning=FALSE}

```
